Repository openshift/pagerduty-operator, pull requests merged in 2019-05, with the labels that each got.

#36 Add a check around request.name length before splicing
  pkg/controller/syncset/syncset_controller.go
Labels: approved, lgtm, size/XS

#34 Create Integrations for each new service
  pkg/controller/clusterdeployment/clusterdeployment_created.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_deleted.go
  pkg/kube/configmap.go
  pkg/kube/syncset.go
  pkg/pagerduty/service.go
Labels: approved, lgtm, size/L

#38 Simplify delete and let k8s clean up a lot of items on NS delete
  pkg/controller/clusterdeployment/clusterdeployment_created.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
Labels: approved, lgtm, size/M

#39 Moved finalizer string to config and updated value
  config/config.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_created.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
Labels: approved, lgtm, size/S

#40 Deploy needed objects for prometheus metrics when the operator comes up
  cmd/manager/main.go
  manifests/06-prometheus-k8s-role.yaml
  manifests/07-prometheus-k8s-rolebinding.yaml
  pkg/metrics/metrics.go
  pkg/metrics/service.go
Labels: approved, lgtm, size/L

#41 Remove legacy finalizers if they exist
  config/config.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_created.go
Labels: approved, lgtm, size/M

#43 If a service already exists in pagerduty use the existing service
  pkg/pagerduty/service.go
Labels: approved, lgtm, size/S

#44 Updated OWNERS to be consistent with other SRE operators
  OWNERS
Labels: approved, lgtm, size/XS

#45 Added additional owners and reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#46 migrate saas repos to ci-int
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm, size/XS
