Repository openshift/pagerduty-operator, pull requests merged in 2019-11, with the labels that each got.

#74 Status.Installed is deprecated, we should use Spec.Installed
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_created.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/S

#76 Added dofinn as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#72 Use secretReference in syncset
  config/config.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_created.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/syncset/syncset_deleted.go
  pkg/kube/syncset.go
  pkg/pagerduty/service.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/L
