Repository openshift/pagerduty-operator, pull requests merged in 2019-07, with the labels that each got.

#49 SREP-1352: Specify an IncidentUrgencyRule for new PD Services
  config/config.go
  pkg/pagerduty/service.go
Labels: approved, lgtm, size/S

#51 using operator-custom-metrics library
  Gopkg.lock
  cmd/manager/main.go
  pkg/localmetrics/localmetrics.go
  vendor/github.com/openshift/operator-custom-metrics/LICENSE
  vendor/github.com/openshift/operator-custom-metrics/example/example.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/builder.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metrics.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metricsconfig.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/service.go
Labels: approved, lgtm, size/XL

#50 Metrics
  cmd/manager/main.go
  pkg/controller/clusterdeployment/clusterdeployment_created.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/L
