Repository openshift/pagerduty-operator, pull requests merged in 2019-10, with the labels that each got.

#63 Add support for a 'noalerts' label
  config/config.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
Labels: approved, lgtm, size/L

#64 Remove SyncSet if noalerts label is added
  config/config.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
  pkg/controller/syncset/syncset_controller.go
Labels: approved, lgtm, size/M

#65 Fixed deletion of SyncSet
  config/config.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/syncset/syncset_deleted.go
  pkg/kube/configmap.go
  pkg/kube/syncset.go
  pkg/pagerduty/service.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/L

#66 Refactor, utility, and tests.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_deleted.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/L

#67 Requeue if check clusterdeployment returns error
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/syncset/syncset_controller.go
Labels: approved, lgtm, size/S

#69 Correct service name to match whats on cluster and in monitoring
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#70 Ignore missing config on delete
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
Labels: approved, lgtm, size/M

#71 Updated OWNERS
  OWNERS
Labels: approved, lgtm, size/XS
