Repository openshift/pagerduty-operator, pull requests merged in 2019-04, with the labels that each got.

#10 Move from the managed label to api.openshift.com/managed
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: size/XS

#9 Add build scripts for app-sre deploy
  config/templates/pagerduty-operator-csv-template.yaml
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
  hack/app_sre_pr_check.sh
  hack/generate-operator-bundle.py
  hack/olm-registry/olm-artifacts-template.yaml
Labels: lgtm, size/L

#12 SREP-1143: Get ready for Prow & osd-operators-registry
  Makefile
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  config/config.go
  project.mk
Labels: size/L

#14 Spec change
  config/config.go
  hack/generate-operator-bundle.py
  manifests/01-namespace.yaml
  manifests/02-role.yaml
  manifests/03-service_account.yaml
  manifests/04-role_binding.yaml
  manifests/05-config.yaml
  manifests/06-operator.yaml
  pkg/pagerduty/service.go
Labels: lgtm, size/M

#15 Update naming of manifests
  hack/generate-operator-bundle.py
  manifests/05-config.yaml
  manifests/05-operator.yaml
  pkg/pagerduty/service.go
Labels: size/M

#16 Add OWNERS file
  OWNERS
Labels: lgtm, size/XS

#17 Update the quay image location
  hack.sh
  manifests/05-operator.yaml
Labels: approved, lgtm, size/XS

#18 Update operator image location
  manifests/05-operator.yaml
Labels: approved, lgtm, size/XS

#19 Update make target and remove hack file
  Makefile
  hack.sh
Labels: approved, lgtm, size/S

#20 Update docker image name
  Makefile
  build/Dockerfile
Labels: approved, lgtm, size/S

#21 Add README
  README.md
Labels: approved, lgtm, size/XS

#22 Listen on all namespaces
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#24 Add clusterdeployments to the role
  manifests/02-role.yaml
  manifests/04-role_binding.yaml
Labels: approved, lgtm, size/S

#26 Migrate to unique PagerDuty service names
  pkg/controller/clusterdeployment/clusterdeployment_created.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
  pkg/controller/syncset/syncset_deleted.go
  pkg/pagerduty/service.go
Labels: approved, lgtm, size/M

#27 Fix a couple edge cases
  pkg/controller/clusterdeployment/clusterdeployment_created.go
  pkg/controller/syncset/syncset_deleted.go
Labels: approved, lgtm, size/M

#28 Allow deletion of syncsets
  manifests/02-role.yaml
Labels: approved, lgtm, size/XS

#31 Change syncset to sync from upsert
  pkg/pagerduty/syncset.go
Labels: approved, lgtm, size/XS

#32 Change the namespace in the syncset
  pkg/pagerduty/syncset.go
Labels: approved, lgtm, size/XS
