Repository openshift/pagerduty-operator, pull requests merged in 2020-07, with the labels that each got.

#100 Upgrade to operator-sdk v0.16.2
  go.mod
  go.sum
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, ok-to-test

#90 Add PagerDutyIntegration CRD
  README.md
  config/config.go
  deploy/crds/pagerduty.openshift.io_pagerdutyintegrations_crd.yaml
  deploy/examples/pagerduty_v1alpha1_pagerdutyintegration_cr.yaml
  hack/generate.sh
  manifests/02-role.yaml
  pkg/apis/addtoscheme_pagerduty_v1alpha1.go
  pkg/apis/pagerduty/v1alpha1/doc.go
  pkg/apis/pagerduty/v1alpha1/pagerdutyintegration_types.go
  pkg/apis/pagerduty/v1alpha1/register.go
  pkg/apis/pagerduty/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_clusterdeployment.go
  pkg/controller/add_pagerdutyintegration.go
  pkg/controller/add_syncset.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
  pkg/controller/pagerdutyintegration/clusterdeployment_created.go
  pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
  pkg/controller/pagerdutyintegration/clusterdeployment_migrate.go
  pkg/controller/pagerdutyintegration/mappers.go
  pkg/controller/pagerdutyintegration/mappers_test.go
  pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
  pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/syncset/syncset_deleted.go
  pkg/kube/configmap.go
  pkg/kube/syncset.go
  pkg/pagerduty/service.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/XXL

#102 Unrevert PagerDutyIntegration & get generate-operator-bundle.py to add CRDs to CSV
  README.md
  build/templates/csv.yaml.tmpl
  config/config.go
  deploy/crds/pagerduty.openshift.io_pagerdutyintegrations_crd.yaml
  deploy/examples/pagerduty_v1alpha1_pagerdutyintegration_cr.yaml
  hack/generate-operator-bundle.py
  hack/generate.sh
  manifests/02-role.yaml
  pkg/apis/addtoscheme_pagerduty_v1alpha1.go
  pkg/apis/pagerduty/v1alpha1/doc.go
  pkg/apis/pagerduty/v1alpha1/pagerdutyintegration_types.go
  pkg/apis/pagerduty/v1alpha1/register.go
  pkg/apis/pagerduty/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_clusterdeployment.go
  pkg/controller/add_pagerdutyintegration.go
  pkg/controller/add_syncset.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_deleted.go
  pkg/controller/pagerdutyintegration/clusterdeployment_created.go
  pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
  pkg/controller/pagerdutyintegration/clusterdeployment_migrate.go
  pkg/controller/pagerdutyintegration/mappers.go
  pkg/controller/pagerdutyintegration/mappers_test.go
  pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
  pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/syncset/syncset_deleted.go
  pkg/kube/configmap.go
  pkg/kube/syncset.go
  pkg/pagerduty/service.go
  pkg/utils/utils.go
Labels: approved, lgtm

#104 Removed legacy migration code
  pkg/controller/pagerdutyintegration/clusterdeployment_migrate.go
  pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
  pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
Labels: approved, lgtm

#99 Add support for new 'ext' noalerts label.
  README.md
  config/config.go
  pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
Labels: approved, lgtm

#103 Add "osd" PagerDutyIntegration CR to the template
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#105 Update OWNERS, adding reviewers
  OWNERS
Labels: approved, lgtm

#108 Fix data type for resolveTimeout and acknowledgeTimeout in template
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#106 Don't hardcode target Secret details in SyncSet
  pkg/controller/pagerdutyintegration/clusterdeployment_created.go
  pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
  pkg/kube/syncset.go
Labels: approved, lgtm

#109 Aesthetic README updates
  README.md
Labels: approved, lgtm
